#+STARTUP: content
#+STARTUP: overview
#+STARTUP: indent
#+STARTUP: latexpreview
#+TITLE: Fundamentals of Image Processing: Structure-based ASCII Art
#+AUTHOR: Rayan Raddatz de Matos, Eduardo Magnus Lazuta


This repository contain the codes, reports and results of our final
work for the Fundamentals of Image Processing (INF01046). The aim of
this repository is to reproduce the results from [[https://ttwong12.github.io/papers/asciiart/asciiart.html][this paper]].

* Creating ASCII Art
** Requirements
This code as created using =python 3.11.2=. We use different libraries
in order to achieve the aimed results. To make it reproducible we
created a python virtual environment. All the libraries used for
running the application are described in the =requirements.txt=. This
file can be used to install all the needed libraries to run the code
using the pip command:

#+begin_src shell :results output :exports both
pip install -r requirements.txt
#+end_src

** Executing the application

The application takes command line arguments in order to create ASCII
Art from a image. A normal execution would use three arguments, the =path= (=-p=), that
indicates the path to the image you want to convert, the =ratio=
(=-r=), who is the color threshold for the image, and the =columns= (=-c=),
the number of columns for the output ASCII Art. You can see all the
options using:

#+begin_src
python ascii.py -h
#+end_src

An example of execution would be:

#+begin_src
python ascii.py --path ../image-tests/image2.jpg --ratio 0.2 -c 40
#+end_src

This makes a ASCII Art made of *40 columns* (text width) from the
=image2.jpg= taking in count only 0.2% of the colors. A good chose of
ration is important to correctly get the image vertices.

#+begin_src
                  7)_
                 ]. I
                _[  .\
               .!    OL
    \\==~~~~~~~/.     )~~~~~~~==\\
    .>_.                      0/`.
      ..O^\.               _-`.
          .O^.           -`.
            ].           !
           _(     _,     .[
           7. \_-`..`^\.  ]_
          o._-`.      .O^\.I
          +`.             O>L
#+end_src

* Members
- Rayan Raddatz de Matos ([[https://github.com/rddtz][@rddtz]])
- Eduardo Magnus Lazuta ([[https://github.com/MagnusLazuta][@MagnusLazuta]])

#+begin_src shell :results output :exports both
                              .O.~*cc`......``c~\.     ,\*cc```````o*-\\,.
                      .#7c`O..                 O~..7`.                ..O``~.
                    ](.0[                        0[                        .[`~.
                  .<\  7.                        0                          ).|+
                 .!O. .(                         0                          .[`.(
                O7O(  7.                         0                           ].`O\
               .(/!. .[                          0                           .[  `.
              0(7].  7.                          0                            ]. .)OI
             .(]OL  .[                           0                            .\  )!O\
            .!0L(   T                            0                             ]. .\IO\
           .!.!7.  .[                            0L                            .+ .\L\0,
          ./.7].   !                              [                             0L ``OL7\
         .7.)O(   oL                              [                              I  .)`.)L
         7.].!.  .!                               [                              0L  .\].).
        7.O(7.   ].                               [                               +   O\$.).
       7..!0L   .(                                [                               O.   `oo.o.
      ]..<.(    ]....,\\~***==ccccc==*~\,.        [       .,<=-/=======**~\\\\\,.. ).   .**.).
     o..\T/. .,00\-^c```.OO\\=#####\\\,..($*\     [   O\c`,\>**^ccccc^^=.. .O``c^**\\.   .$+ ^.
    .L 0(]..O,.\\~--*co\$\\>===*****==#\,`$*#,    [  >.~$^$o#>======\0`00L\ccc^**=~\\\\,..O$..).
  O/~*:`....    ....,,.\\\\\\****^^^**=#\,OO.0....[.,(``.,\\\----~=###\\\\,,,,....       ...`o~\~.
\*<ccc```````.......                     .0cc`.......ccc..                   ........OOO````ccccc!<.
#+end_src
